const questions = [
  "Who is more likely to become a millionaire?",
  "Who would survive longer in a zombie apocalypse?",
  "Who is more likely to forget their own birthday?",
  "Who would make a better stand-up comedian?",
  "Who would win in a cooking competition?",
  "Who is more likely to adopt a stray animal?",
  "Who would make the better detective?",
  "Who is more likely to binge-watch an entire TV series in one day?",
  "Who would win in a karaoke contest?",
  "Who is more likely to accidentally send a text to the wrong person?",
  "Who would be the better astronaut?",
  "Who is more likely to invent something useful?",
  "Who would make the better spy?",
  "Who is more likely to eat dessert before dinner?",
  "Who is more likely to prank a friend?",
  "Who is more likely to write a best-selling novel?",
  "Who would win in a trivia contest?",
  "Who is more likely to start a band?",
  "Who is more likely to get lost in their own neighborhood?",
  "Who would be the better public speaker?",
  "Who is more likely to become a famous actor or actress?",
  "Who would make the best superhero?",
  "Who is more likely to win a dance competition?",
  "Who would survive longest on a deserted island?",
  "Who is more likely to start their own company?",
  "Who would make the better teacher?",
  "Who is more likely to laugh at the wrong moment?",
  "Who would be better at solving a Rubik's cube?",
  "Who is more likely to go skydiving?",
  "Who would win in an arm-wrestling match?",
  "Who is more likely to cry during a movie?",
  "Who would make the better president?",
  "Who is more likely to get a tattoo they regret?",
  "Who would be the best tour guide in a new city?",
  "Who is more likely to win a staring contest?",
  "Who would make the better artist?",
  "Who is more likely to lose their phone?",
  "Who would be the better game show contestant?",
  "Who is more likely to forget where they parked their car?",
  "Who would make the best travel companion?",
  "Who is more likely to wake up late for an important event?",
  "Who would win a hide-and-seek game?",
  "Who is more likely to win a lottery ticket?",
  "Who would survive longest in the wild?",
  "Who is more likely to eat the last slice of pizza?",
  "Who would be the better poker player?",
  "Who is more likely to get caught in a lie?",
  "Who would make the better parent?",
  "Who is more likely to talk their way out of trouble?",
  "Who would make the better athlete?",
  "Who is more likely to build a robot?",
  "Who would win in a board game?",
  "Who is more likely to forget someone's birthday?",
  "Who would make the better actor in a play?",
  "Who is more likely to own an exotic pet?",
  "Who would be better at imitating accents?",
  "Who is more likely to sleep through an alarm?",
  "Who would be the better party planner?",
  "Who is more likely to run a marathon?",
  "Who would survive a week without their phone?",
  "Who is more likely to try a bizarre food?",
  "Who would win in a water balloon fight?",
  "Who is more likely to spend all day at the beach?",
  "Who would make the better DJ?",
  "Who is more likely to win a science fair?",
  "Who would make the better fashion designer?",
  "Who is more likely to enjoy a horror movie?",
  "Who would win a singing competition?",
  "Who is more likely to forget their keys?",
  "Who would make the better comedian?",
  "Who is more likely to adopt a random hobby?",
  "Who would win in a video game competition?",
  "Who is more likely to keep a secret?",
  "Who would make the better novelist?",
  "Who is more likely to get a speeding ticket?",
  "Who would be better at solving a mystery?",
  "Who is more likely to take a spontaneous trip?",
  "Who would survive longest in a haunted house?",
  "Who is more likely to accidentally start a trend?",
  "Who would make the better magician?",
  "Who is more likely to climb a mountain?",
  "Who would make the best campfire storyteller?",
  "Who is more likely to start a podcast?",
  "Who would be the better motivational speaker?",
  "Who is more likely to remember a random fact?",
  "Who would make the better singer in a band?",
  "Who is more likely to trip over nothing?",
  "Who would win in a chess match?",
  "Who is more likely to host a dinner party?",
  "Who would be the better personal trainer?",
  "Who is more likely to try an extreme sport?",
  "Who would win in a tug-of-war match?",
  "Who is more likely to write a viral tweet?",
  "Who would make the better pilot?",
  "Who is more likely to ace a math test?",
  "Who would be the better fashion model?",
  "Who is more likely to lose their wallet?",
  "Who would win a hotdog-eating contest?",
  "Who is more likely to organize a charity event?",
  "Who would win in a spelling bee?",
  "Who is more likely to remember everyone's name?",
  "Who would be the better babysitter?",
  "Who is more likely to own a pet snake?",
  "Who would survive longest in space?",
  "Who is more likely to sleepwalk?",
  "Who would be better at building a treehouse?",
  "Who is more likely to get caught in an embarrassing situation?",
  "Who would make the best fashion critic?",
  "Who is more likely to get stranded in an elevator?",
  "Who would be the better photographer?",
  "Who is more likely to memorize all the lyrics to a song?",
  "Who would be better at fixing a car?",
  "Who is more likely to win a ping-pong tournament?",
  "Who would survive longer in a survival reality TV show?",
  "Who is more likely to write a love letter?",
  "Who would win a competitive eating contest?",
  "Who is more likely to name their pet something unusual?",
  "Who would be the better professional chef?",
  "Who is more likely to solve a complex riddle?",
  "Who would win in a limbo competition?",
  "Who is more likely to get recognized in public?",
  "Who would make the best lifeguard?",
  "Who is more likely to adopt a minimalist lifestyle?",
  "Who would be the better builder in Minecraft?",
  "Who is more likely to know a random historical fact?",
  "Who would win a staring contest?",
  "Who is more likely to sleep through a thunderstorm?",
  "Who would make the best escape room teammate?",
  "Who is more likely to lead a protest?",
  "Who would be better at painting a masterpiece?",
  "Who is more likely to take up gardening?",
  "Who would win a talent show?",
  "Who is more likely to master a musical instrument?",
  "Who would survive longest in an alien invasion?",
  "Who is more likely to spend hours on a craft project?",
  "Who would be the better treasure hunter?",
  "Who is more likely to win a rock-paper-scissors championship?",
  "Who would make the better zookeeper?",
  "Who is more likely to throw an epic surprise party?",
  "Who would be the better ballroom dancer?",
  "Who is more likely to spend all day reading?",
  "Who would survive longest in an arctic expedition?",
  "Who is more likely to win a local election?",
  "Who would make the better fantasy author?",
  "Who is more likely to forget a friend's birthday?",
  "Who would win in a rap battle?",
  "Who is more likely to build a snowman?",
  "Who would make the best animal whisperer?",
  "Who is more likely to binge-watch documentaries?",
  "Who would be better at creating a viral video?",
  "Who is more likely to join a circus?",
  "Who would make the better escape artist?",
  "Who is more likely to learn a foreign language fluently?",
  "Who would win in a soapbox derby race?",
  "Who is more likely to get a funny tattoo?"
];

module.exports = {
  async getQuestion () {
    const maxValue = questions.length;

    const index = Math.round(Math.random() * maxValue);

    return questions[index];
  }
}